version: '3'

services:
  admin:
    build:
      context: ./admin
      target: dev
    volumes:
      - "./admin/src:/app/src"
      - "./admin/public:/app/public"

  web:
    build:
      context: ./web
      target: dev
    volumes:
      - "./web/src:/app/src"
      - "./web/public:/app/public"
  
  
  api:
    build:
      context: ./api
      target: dev
    volumes:
      - "./api/app:/app/app"
