version: '3'

services:
  admin:
    build:
      context: ./admin
      target: dev
    volumes:
      - "./admin/src:/app/src"
      - "./admin/public:/app/public"

  web:
    build:
      context: ./web
      target: dev
    environment:
      REACT_APP_HOST: ${DOMAIN:-achieve.localhost}
    volumes:
      - "./web/src:/app/src"
      - "./web/public:/app/public"
  
  
  api:
    build:
      context: ./api
      target: dev
    volumes:
      - "./api/htm_achiever:/app/htm_achiever"
