http:
  middlewares:
    cors:
      headers:
        accessControlAllowHeaders: "*"
        accessControlAllowMethods: "*"
        accessControlAllowCredentials: "true"
        accessControlAllowOriginListRegex: 'https?://([^.]+\.)?achieve.localhost(/.*)?'
